version: "3.8"
services:
  mongodb:
   image: mongo:4.4
   restart: always
   ports:
    - 27017:27017
   environment:
    - MONGO_INITDB_ROOT_USERNAME=adminUser
    - MONGO_INITDB_ROOT_PASSWORD=adminPassword

  expressapi:
   build: .
   restart: always
   ports:
    - 8001:8001
   depends_on:
    - mongodb
   environment:
     Port: 8001
     MONGO_URI: mongodb://adminUser:adminPassword@mongodb:27017/?authMechanism=DEFAULT&authSource=Ms-users
     Secret: "R7bqpE7rsG6CZ7uERMKfKvamnGwUHu2QAjZ87BPLE3YGKuJyeQg962V7kCEhNDrFS3LYfCTX4ETz4p34RfLJkcaEBj2dNE3vDnq5Gfm5rsJWTrRAhXDm2EstPtuEbFpvyAZv2HCNJzjBjJDry7M2qHz6Xx7LqhHrZ3L2RaXUjBAEpHZsrqFduVQSdsLETbTJpsEvpJ9g5xPdKwDNy9V6qKuj2hpb7uXMUqmSKNMQTRtDEdCGxQtEwNscdbvGSAN5"
 
volumes:
   mongodb: